# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 4.4

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/sbin/cmake

# The command to remove a file.
RM = /usr/sbin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/hypokoto/minimal/shell

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/hypokoto/minimal

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/usr/sbin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/sbin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/usr/sbin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/usr/sbin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/usr/sbin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/usr/sbin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/usr/sbin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/usr/sbin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/hypokoto/minimal/CMakeFiles /home/hypokoto/minimal//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/hypokoto/minimal/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named nanovg_lib

# Build rule for target.
nanovg_lib: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 nanovg_lib
.PHONY : nanovg_lib

# fast build rule for target.
nanovg_lib/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nanovg_lib.dir/build.make CMakeFiles/nanovg_lib.dir/build
.PHONY : nanovg_lib/fast

#=============================================================================
# Target rules for targets named minimal_shell

# Build rule for target.
minimal_shell: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 minimal_shell
.PHONY : minimal_shell

# fast build rule for target.
minimal_shell/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/minimal_shell.dir/build.make CMakeFiles/minimal_shell.dir/build
.PHONY : minimal_shell/fast

_deps/nanovg-src/src/nanovg.o: _deps/nanovg-src/src/nanovg.c.o
.PHONY : _deps/nanovg-src/src/nanovg.o

# target to build an object file
_deps/nanovg-src/src/nanovg.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nanovg_lib.dir/build.make CMakeFiles/nanovg_lib.dir/_deps/nanovg-src/src/nanovg.c.o
.PHONY : _deps/nanovg-src/src/nanovg.c.o

_deps/nanovg-src/src/nanovg.i: _deps/nanovg-src/src/nanovg.c.i
.PHONY : _deps/nanovg-src/src/nanovg.i

# target to preprocess a source file
_deps/nanovg-src/src/nanovg.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nanovg_lib.dir/build.make CMakeFiles/nanovg_lib.dir/_deps/nanovg-src/src/nanovg.c.i
.PHONY : _deps/nanovg-src/src/nanovg.c.i

_deps/nanovg-src/src/nanovg.s: _deps/nanovg-src/src/nanovg.c.s
.PHONY : _deps/nanovg-src/src/nanovg.s

# target to generate assembly for a file
_deps/nanovg-src/src/nanovg.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nanovg_lib.dir/build.make CMakeFiles/nanovg_lib.dir/_deps/nanovg-src/src/nanovg.c.s
.PHONY : _deps/nanovg-src/src/nanovg.c.s

src/core/animation.o: src/core/animation.cpp.o
.PHONY : src/core/animation.o

# target to build an object file
src/core/animation.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/minimal_shell.dir/build.make CMakeFiles/minimal_shell.dir/src/core/animation.cpp.o
.PHONY : src/core/animation.cpp.o

src/core/animation.i: src/core/animation.cpp.i
.PHONY : src/core/animation.i

# target to preprocess a source file
src/core/animation.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/minimal_shell.dir/build.make CMakeFiles/minimal_shell.dir/src/core/animation.cpp.i
.PHONY : src/core/animation.cpp.i

src/core/animation.s: src/core/animation.cpp.s
.PHONY : src/core/animation.s

# target to generate assembly for a file
src/core/animation.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/minimal_shell.dir/build.make CMakeFiles/minimal_shell.dir/src/core/animation.cpp.s
.PHONY : src/core/animation.cpp.s

src/core/animation_manager.o: src/core/animation_manager.cpp.o
.PHONY : src/core/animation_manager.o

# target to build an object file
src/core/animation_manager.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/minimal_shell.dir/build.make CMakeFiles/minimal_shell.dir/src/core/animation_manager.cpp.o
.PHONY : src/core/animation_manager.cpp.o

src/core/animation_manager.i: src/core/animation_manager.cpp.i
.PHONY : src/core/animation_manager.i

# target to preprocess a source file
src/core/animation_manager.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/minimal_shell.dir/build.make CMakeFiles/minimal_shell.dir/src/core/animation_manager.cpp.i
.PHONY : src/core/animation_manager.cpp.i

src/core/animation_manager.s: src/core/animation_manager.cpp.s
.PHONY : src/core/animation_manager.s

# target to generate assembly for a file
src/core/animation_manager.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/minimal_shell.dir/build.make CMakeFiles/minimal_shell.dir/src/core/animation_manager.cpp.s
.PHONY : src/core/animation_manager.cpp.s

src/core/dbus_client.o: src/core/dbus_client.cpp.o
.PHONY : src/core/dbus_client.o

# target to build an object file
src/core/dbus_client.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/minimal_shell.dir/build.make CMakeFiles/minimal_shell.dir/src/core/dbus_client.cpp.o
.PHONY : src/core/dbus_client.cpp.o

src/core/dbus_client.i: src/core/dbus_client.cpp.i
.PHONY : src/core/dbus_client.i

# target to preprocess a source file
src/core/dbus_client.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/minimal_shell.dir/build.make CMakeFiles/minimal_shell.dir/src/core/dbus_client.cpp.i
.PHONY : src/core/dbus_client.cpp.i

src/core/dbus_client.s: src/core/dbus_client.cpp.s
.PHONY : src/core/dbus_client.s

# target to generate assembly for a file
src/core/dbus_client.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/minimal_shell.dir/build.make CMakeFiles/minimal_shell.dir/src/core/dbus_client.cpp.s
.PHONY : src/core/dbus_client.cpp.s

src/core/event_loop.o: src/core/event_loop.cpp.o
.PHONY : src/core/event_loop.o

# target to build an object file
src/core/event_loop.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/minimal_shell.dir/build.make CMakeFiles/minimal_shell.dir/src/core/event_loop.cpp.o
.PHONY : src/core/event_loop.cpp.o

src/core/event_loop.i: src/core/event_loop.cpp.i
.PHONY : src/core/event_loop.i

# target to preprocess a source file
src/core/event_loop.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/minimal_shell.dir/build.make CMakeFiles/minimal_shell.dir/src/core/event_loop.cpp.i
.PHONY : src/core/event_loop.cpp.i

src/core/event_loop.s: src/core/event_loop.cpp.s
.PHONY : src/core/event_loop.s

# target to generate assembly for a file
src/core/event_loop.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/minimal_shell.dir/build.make CMakeFiles/minimal_shell.dir/src/core/event_loop.cpp.s
.PHONY : src/core/event_loop.cpp.s

src/ipc/hypr_socket.o: src/ipc/hypr_socket.cpp.o
.PHONY : src/ipc/hypr_socket.o

# target to build an object file
src/ipc/hypr_socket.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/minimal_shell.dir/build.make CMakeFiles/minimal_shell.dir/src/ipc/hypr_socket.cpp.o
.PHONY : src/ipc/hypr_socket.cpp.o

src/ipc/hypr_socket.i: src/ipc/hypr_socket.cpp.i
.PHONY : src/ipc/hypr_socket.i

# target to preprocess a source file
src/ipc/hypr_socket.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/minimal_shell.dir/build.make CMakeFiles/minimal_shell.dir/src/ipc/hypr_socket.cpp.i
.PHONY : src/ipc/hypr_socket.cpp.i

src/ipc/hypr_socket.s: src/ipc/hypr_socket.cpp.s
.PHONY : src/ipc/hypr_socket.s

# target to generate assembly for a file
src/ipc/hypr_socket.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/minimal_shell.dir/build.make CMakeFiles/minimal_shell.dir/src/ipc/hypr_socket.cpp.s
.PHONY : src/ipc/hypr_socket.cpp.s

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/minimal_shell.dir/build.make CMakeFiles/minimal_shell.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/minimal_shell.dir/build.make CMakeFiles/minimal_shell.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/minimal_shell.dir/build.make CMakeFiles/minimal_shell.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/render/layout.o: src/render/layout.cpp.o
.PHONY : src/render/layout.o

# target to build an object file
src/render/layout.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/minimal_shell.dir/build.make CMakeFiles/minimal_shell.dir/src/render/layout.cpp.o
.PHONY : src/render/layout.cpp.o

src/render/layout.i: src/render/layout.cpp.i
.PHONY : src/render/layout.i

# target to preprocess a source file
src/render/layout.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/minimal_shell.dir/build.make CMakeFiles/minimal_shell.dir/src/render/layout.cpp.i
.PHONY : src/render/layout.cpp.i

src/render/layout.s: src/render/layout.cpp.s
.PHONY : src/render/layout.s

# target to generate assembly for a file
src/render/layout.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/minimal_shell.dir/build.make CMakeFiles/minimal_shell.dir/src/render/layout.cpp.s
.PHONY : src/render/layout.cpp.s

src/render/renderer.o: src/render/renderer.cpp.o
.PHONY : src/render/renderer.o

# target to build an object file
src/render/renderer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/minimal_shell.dir/build.make CMakeFiles/minimal_shell.dir/src/render/renderer.cpp.o
.PHONY : src/render/renderer.cpp.o

src/render/renderer.i: src/render/renderer.cpp.i
.PHONY : src/render/renderer.i

# target to preprocess a source file
src/render/renderer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/minimal_shell.dir/build.make CMakeFiles/minimal_shell.dir/src/render/renderer.cpp.i
.PHONY : src/render/renderer.cpp.i

src/render/renderer.s: src/render/renderer.cpp.s
.PHONY : src/render/renderer.s

# target to generate assembly for a file
src/render/renderer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/minimal_shell.dir/build.make CMakeFiles/minimal_shell.dir/src/render/renderer.cpp.s
.PHONY : src/render/renderer.cpp.s

src/render/theme.o: src/render/theme.cpp.o
.PHONY : src/render/theme.o

# target to build an object file
src/render/theme.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/minimal_shell.dir/build.make CMakeFiles/minimal_shell.dir/src/render/theme.cpp.o
.PHONY : src/render/theme.cpp.o

src/render/theme.i: src/render/theme.cpp.i
.PHONY : src/render/theme.i

# target to preprocess a source file
src/render/theme.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/minimal_shell.dir/build.make CMakeFiles/minimal_shell.dir/src/render/theme.cpp.i
.PHONY : src/render/theme.cpp.i

src/render/theme.s: src/render/theme.cpp.s
.PHONY : src/render/theme.s

# target to generate assembly for a file
src/render/theme.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/minimal_shell.dir/build.make CMakeFiles/minimal_shell.dir/src/render/theme.cpp.s
.PHONY : src/render/theme.cpp.s

src/wayland/layer_surface.o: src/wayland/layer_surface.cpp.o
.PHONY : src/wayland/layer_surface.o

# target to build an object file
src/wayland/layer_surface.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/minimal_shell.dir/build.make CMakeFiles/minimal_shell.dir/src/wayland/layer_surface.cpp.o
.PHONY : src/wayland/layer_surface.cpp.o

src/wayland/layer_surface.i: src/wayland/layer_surface.cpp.i
.PHONY : src/wayland/layer_surface.i

# target to preprocess a source file
src/wayland/layer_surface.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/minimal_shell.dir/build.make CMakeFiles/minimal_shell.dir/src/wayland/layer_surface.cpp.i
.PHONY : src/wayland/layer_surface.cpp.i

src/wayland/layer_surface.s: src/wayland/layer_surface.cpp.s
.PHONY : src/wayland/layer_surface.s

# target to generate assembly for a file
src/wayland/layer_surface.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/minimal_shell.dir/build.make CMakeFiles/minimal_shell.dir/src/wayland/layer_surface.cpp.s
.PHONY : src/wayland/layer_surface.cpp.s

wlr-layer-shell-unstable-v1-protocol.o: wlr-layer-shell-unstable-v1-protocol.c.o
.PHONY : wlr-layer-shell-unstable-v1-protocol.o

# target to build an object file
wlr-layer-shell-unstable-v1-protocol.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/minimal_shell.dir/build.make CMakeFiles/minimal_shell.dir/wlr-layer-shell-unstable-v1-protocol.c.o
.PHONY : wlr-layer-shell-unstable-v1-protocol.c.o

wlr-layer-shell-unstable-v1-protocol.i: wlr-layer-shell-unstable-v1-protocol.c.i
.PHONY : wlr-layer-shell-unstable-v1-protocol.i

# target to preprocess a source file
wlr-layer-shell-unstable-v1-protocol.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/minimal_shell.dir/build.make CMakeFiles/minimal_shell.dir/wlr-layer-shell-unstable-v1-protocol.c.i
.PHONY : wlr-layer-shell-unstable-v1-protocol.c.i

wlr-layer-shell-unstable-v1-protocol.s: wlr-layer-shell-unstable-v1-protocol.c.s
.PHONY : wlr-layer-shell-unstable-v1-protocol.s

# target to generate assembly for a file
wlr-layer-shell-unstable-v1-protocol.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/minimal_shell.dir/build.make CMakeFiles/minimal_shell.dir/wlr-layer-shell-unstable-v1-protocol.c.s
.PHONY : wlr-layer-shell-unstable-v1-protocol.c.s

xdg-shell-protocol.o: xdg-shell-protocol.c.o
.PHONY : xdg-shell-protocol.o

# target to build an object file
xdg-shell-protocol.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/minimal_shell.dir/build.make CMakeFiles/minimal_shell.dir/xdg-shell-protocol.c.o
.PHONY : xdg-shell-protocol.c.o

xdg-shell-protocol.i: xdg-shell-protocol.c.i
.PHONY : xdg-shell-protocol.i

# target to preprocess a source file
xdg-shell-protocol.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/minimal_shell.dir/build.make CMakeFiles/minimal_shell.dir/xdg-shell-protocol.c.i
.PHONY : xdg-shell-protocol.c.i

xdg-shell-protocol.s: xdg-shell-protocol.c.s
.PHONY : xdg-shell-protocol.s

# target to generate assembly for a file
xdg-shell-protocol.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/minimal_shell.dir/build.make CMakeFiles/minimal_shell.dir/xdg-shell-protocol.c.s
.PHONY : xdg-shell-protocol.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... minimal_shell"
	@echo "... nanovg_lib"
	@echo "... _deps/nanovg-src/src/nanovg.o"
	@echo "... _deps/nanovg-src/src/nanovg.i"
	@echo "... _deps/nanovg-src/src/nanovg.s"
	@echo "... src/core/animation.o"
	@echo "... src/core/animation.i"
	@echo "... src/core/animation.s"
	@echo "... src/core/animation_manager.o"
	@echo "... src/core/animation_manager.i"
	@echo "... src/core/animation_manager.s"
	@echo "... src/core/dbus_client.o"
	@echo "... src/core/dbus_client.i"
	@echo "... src/core/dbus_client.s"
	@echo "... src/core/event_loop.o"
	@echo "... src/core/event_loop.i"
	@echo "... src/core/event_loop.s"
	@echo "... src/ipc/hypr_socket.o"
	@echo "... src/ipc/hypr_socket.i"
	@echo "... src/ipc/hypr_socket.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/render/layout.o"
	@echo "... src/render/layout.i"
	@echo "... src/render/layout.s"
	@echo "... src/render/renderer.o"
	@echo "... src/render/renderer.i"
	@echo "... src/render/renderer.s"
	@echo "... src/render/theme.o"
	@echo "... src/render/theme.i"
	@echo "... src/render/theme.s"
	@echo "... src/wayland/layer_surface.o"
	@echo "... src/wayland/layer_surface.i"
	@echo "... src/wayland/layer_surface.s"
	@echo "... wlr-layer-shell-unstable-v1-protocol.o"
	@echo "... wlr-layer-shell-unstable-v1-protocol.i"
	@echo "... wlr-layer-shell-unstable-v1-protocol.s"
	@echo "... xdg-shell-protocol.o"
	@echo "... xdg-shell-protocol.i"
	@echo "... xdg-shell-protocol.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system
