/* Generated by scripts/gen-palette.sh — DO NOT edit directly. */
#ifndef MINOSD_PALETTE_H
#define MINOSD_PALETTE_H

#define COLOR_BG      0xE60E091D
#define COLOR_BORDER  0xFF342946
#define COLOR_TRACK   0xFF241B2F
#define COLOR_BAR     0xFF14B9B5
#define COLOR_MUTED   0xFFBE3F50
#define COLOR_TEXT    0xFFEDE6F5

#endif
