use serde::{Deserialize, Serialize};
use std::fs;
use std::path::Path;

#[derive(Debug, Serialize, Deserialize, Clone)]
pub struct ThemeTokens {
    pub background: String,
    pub surface: String,
    pub overlay: String,
    pub text: String,
    pub muted: String,
    pub primary: String,
    pub secondary: String,
    pub highlight: String,
    pub success: String,
    pub warning: String,
    pub danger: String,
    pub info: String,
}

#[derive(Debug, Serialize, Deserialize, Clone)]
pub struct ThemeMeta {
    pub name: String,
    pub author: String,
    pub description: String,
}

#[derive(Debug, Serialize, Deserialize, Clone)]
pub struct Theme {
    pub meta: ThemeMeta,
    pub tokens: ThemeTokens,
}

impl Theme {
    pub fn load_from_file<P: AsRef<Path>>(path: P) -> Result<Self, String> {
        let content = fs::read_to_string(path).map_err(|e| e.to_string())?;
        let theme: Theme = toml::from_str(&content).map_err(|e| e.to_string())?;
        theme.validate()?;
        Ok(theme)
    }

    pub fn validate(&self) -> Result<(), String> {
        let hex_regex = |val: &str| -> bool {
            val.starts_with('#') && (val.len() == 7 || val.len() == 9)
        };

        let tokens = [
            ("background", &self.tokens.background),
            ("surface", &self.tokens.surface),
            ("overlay", &self.tokens.overlay),
            ("text", &self.tokens.text),
            ("muted", &self.tokens.muted),
            ("primary", &self.tokens.primary),
            ("secondary", &self.tokens.secondary),
            ("highlight", &self.tokens.highlight),
            ("success", &self.tokens.success),
            ("warning", &self.tokens.warning),
            ("danger", &self.tokens.danger),
            ("info", &self.tokens.info),
        ];

        for (name, val) in tokens.iter() {
            if !hex_regex(val) {
                return Err(format!("Invalid hex color for token '{}': {}", name, val));
            }
        }
        Ok(())
    }

    pub fn generate_rofi_theme(&self) -> String {
        format!(
            r#"/**
 * theme.rasi — Bento Minimal Centralized Token Palette
 * Generated by minimalctl — DO NOT edit directly.
 */

* {{
    bg:        {};
    surface:   {};
    overlay:   {};
    fg:        {};
    muted:     {};
    primary:   {};
    secondary: {};
    highlight: {};
    success:   {};
    warning:   {};
    danger:    {};
    info:      {};

    bg-trans:      {}EE;
    surface-trans: {}F2;
    overlay-trans: {}AA;

    font: "AdwaitaMono Nerd Font 10.5";

    background-color: transparent;
    text-color:        @fg;
    margin:  0px;
    padding: 0px;
    spacing: 0px;
}}

window {{
    background-color: @surface-trans;
    border:           1px;
    border-color:     @overlay;
    border-radius:    12px;
}}

mainbox {{
    background-color: transparent;
    padding:          20px;
    spacing:          14px;
}}

inputbar {{
    background-color: @overlay;
    border-radius:    8px;
    padding:          10px 14px;
    spacing:          10px;
    border:           1px;
    border-color:     {}33;
}}

listview {{
    spacing:          6px;
    background-color: transparent;
    border:           0px;
}}

element {{
    padding:          16px 20px;
    border-radius:    12px;
    background-color: @surface;
    border:           1px;
    border-color:     @overlay;
}}

element selected {{
    background-color: @overlay;
    border-color:     @primary;
    text-color:       @fg;
}}

element normal {{
    background-color: transparent;
    text-color:       @fg;
}}
"#,
            self.tokens.background,
            self.tokens.surface,
            self.tokens.overlay,
            self.tokens.text,
            self.tokens.muted,
            self.tokens.primary,
            self.tokens.secondary,
            self.tokens.highlight,
            self.tokens.success,
            self.tokens.warning,
            self.tokens.danger,
            self.tokens.info,
            self.tokens.background,
            self.tokens.surface,
            self.tokens.overlay,
            self.tokens.primary
        )
    }

    pub fn generate_mako_config(&self) -> String {
        format!(
            r#"# Minimal Mako Config — Bento Pill Notifications & OSD
# Generated by minimalctl — DO NOT edit directly.

font=AdwaitaMono Nerd Font 10
background-color={}
text-color={}
border-color={}
border-size=1
border-radius=12
padding=14,16
margin=10
width=320
height=110
default-timeout=4000
progress-color=source {}

[urgency=low]
border-color={}

[urgency=normal]
border-color={}

[urgency=critical]
border-color={}
default-timeout=0

[app-name="minimal-osd"]
group-by=category
default-timeout=1500
border-color={}
progress-color=source {}
"#,
            self.tokens.surface,
            self.tokens.text,
            self.tokens.overlay,
            self.tokens.primary,
            self.tokens.overlay,
            self.tokens.overlay,
            self.tokens.danger,
            self.tokens.overlay,
            self.tokens.primary
        )
    }

    pub fn generate_kitty_conf(&self) -> String {
        format!(
            r#"# Minimal Kitty Config — Bento Aesthetics
# Generated by minimalctl — DO NOT edit directly.
font_family      AdwaitaMono Nerd Font
bold_font        auto
italic_font      auto
font_size        11.0

background_opacity 1.0
window_padding_width 12
confirm_os_window_close 0

cursor_shape beam
cursor_blink_interval 0

foreground            {}
background            {}
selection_foreground  {}
selection_background  {}

cursor                {}
cursor_text_color     {}

url_color             {}

color0  {}
color8  {}
color1  {}
color9  {}
color2  {}
color10 {}
color3  {}
color11 {}
color4  {}
color12 {}
color5  {}
color13 {}
color6  {}
color14 {}
color7  {}
color15 {}

active_border_color   {}
inactive_border_color {}
tab_bar_style         fade
tab_fade              0.5 1
tab_bar_background    {}
active_tab_background {}
active_tab_foreground {}
inactive_tab_background {}
inactive_tab_foreground {}

allow_remote_control yes
enabled_layouts tall,fat,grid,stack
"#,
            self.tokens.text,
            self.tokens.background,
            self.tokens.background,
            self.tokens.primary,
            self.tokens.primary,
            self.tokens.background,
            self.tokens.secondary,
            self.tokens.surface,
            self.tokens.muted,
            self.tokens.danger,
            self.tokens.danger,
            self.tokens.success,
            self.tokens.success,
            self.tokens.warning,
            self.tokens.warning,
            self.tokens.secondary,
            self.tokens.secondary,
            self.tokens.highlight,
            self.tokens.highlight,
            self.tokens.info,
            self.tokens.primary,
            self.tokens.text,
            self.tokens.text,
            self.tokens.primary,
            self.tokens.overlay,
            self.tokens.background,
            self.tokens.overlay,
            self.tokens.primary,
            self.tokens.surface,
            self.tokens.muted
        )
    }

    pub fn generate_waybar_style(&self) -> String {
        format!(
            r#"/* ============================================================
   MINIMAL BENTO — 3-Pill Waybar Design System
   Generated by minimalctl — DO NOT edit directly.
   ============================================================ */
@define-color background {};
@define-color surface    {};
@define-color overlay    {};
@define-color text       {};
@define-color muted      {};
@define-color primary    {};
@define-color secondary  {};
@define-color highlight  {};
@define-color success    {};
@define-color warning    {};
@define-color danger     {};
@define-color info       {};

/* ============================================================
   BASE RESET & TYPOGRAPHY
   ============================================================ */
* {{
    font-family: "AdwaitaMono Nerd Font", "JetBrainsMono NF", monospace;
    font-size: 11.5px;
    font-weight: 600;
    letter-spacing: -0.01em;
    min-height: 0;
    margin: 0;
    padding: 0;
    border: none;
    border-radius: 0;
    color: @text;
}}

window#waybar {{
    background: transparent;
    color: @text;
}}

/* ============================================================
   THREE BENTO PILL CONTAINERS
   ============================================================ */
box#left {{
    background-color: rgba(17, 22, 31, 0.92);
    border: 1px solid rgba(25, 33, 45, 0.85);
    border-radius: 12px;
    padding: 2px 10px;
    margin: 0;
}}

box#center {{
    background-color: rgba(17, 22, 31, 0.92);
    border: 1px solid rgba(25, 33, 45, 0.85);
    border-radius: 12px;
    padding: 2px 14px;
    margin: 0;
}}

box#right {{
    background-color: rgba(17, 22, 31, 0.92);
    border: 1px solid rgba(25, 33, 45, 0.85);
    border-radius: 12px;
    padding: 2px 10px;
    margin: 0;
}}

/* ============================================================
   MODULE BASE LAYOUT & FEEDBACK
   ============================================================ */
#custom-logo,
#custom-security,
#workspaces,
#submap,
#window,
#clock,
#pulseaudio,
#backlight,
#network,
#cpu,
#memory,
#battery,
#tray {{
    padding: 2px 6px;
    margin: 1px 2px;
    border-radius: 6px;
    transition: all 0.2s ease-in-out;
}}

#custom-logo:active,
#custom-security:active,
#workspaces button:active,
#clock:active,
#network:active,
#battery:active,
#pulseaudio:active {{
    background-color: rgba(232, 237, 245, 0.08);
}}

/* ============================================================
   LEFT PILL — Logo, Workspaces, Window
   ============================================================ */
#custom-logo {{
    color: @primary;
    font-size: 13.5px;
    padding: 2px 8px;
    margin-right: 4px;
}}

#custom-logo:hover {{
    color: @text;
    background-color: rgba(125, 211, 252, 0.12);
}}

#workspaces button {{
    padding: 2px 8px;
    margin: 1px 2px;
    color: @muted;
    background: transparent;
    border-radius: 6px;
    border: 1px solid transparent;
    transition: all 0.2s ease;
}}

#workspaces button.active {{
    color: @text;
    background-color: @overlay;
    border-color: rgba(125, 211, 252, 0.4);
}}

#workspaces button.urgent {{
    color: @danger;
    background-color: rgba(240, 128, 128, 0.15);
    border-color: rgba(240, 128, 128, 0.4);
}}

#workspaces button:hover:not(.active) {{
    background-color: rgba(232, 237, 245, 0.05);
    color: @text;
}}

#submap {{
    color: @highlight;
    background-color: rgba(180, 167, 255, 0.12);
    border-radius: 6px;
    border: 1px solid rgba(180, 167, 255, 0.3);
    margin-left: 6px;
}}

#window {{
    color: @muted;
    font-weight: 500;
    border-left: 1px solid @overlay;
    margin-left: 6px;
    padding-left: 10px;
}}

/* ============================================================
   CENTER PILL — Clock Anchor
   ============================================================ */
#clock {{
    color: @text;
    font-weight: 600;
    padding: 2px 6px;
}}

#clock:hover {{
    color: @primary;
}}

/* ============================================================
   RIGHT PILL — Metrics & Controls
   ============================================================ */
#custom-security {{
    font-size: 12px;
    padding: 2px 8px;
    margin-right: 4px;
    border-radius: 6px;
}}

#custom-security.secure {{
    color: @success;
}}

#custom-security.warning {{
    color: @warning;
    background-color: rgba(232, 199, 123, 0.10);
}}

#custom-security.degraded {{
    color: @danger;
    background-color: rgba(240, 128, 128, 0.15);
}}

#custom-security:hover {{
    background-color: rgba(232, 237, 245, 0.08);
}}

#pulseaudio {{
    color: @muted;
    font-weight: 500;
}}

#pulseaudio.muted {{
    color: @muted;
    opacity: 0.6;
}}

#network {{
    color: @muted;
    font-weight: 500;
}}

#network.disconnected {{
    color: @danger;
    background-color: rgba(240, 128, 128, 0.12);
    border-radius: 6px;
}}

/* Discrete Battery States (No Gradients) */
#battery {{
    color: @muted;
    font-weight: 500;
}}

#battery.charging {{
    color: @success;
}}

#battery.warning:not(.charging) {{
    color: @warning;
}}

#battery.critical:not(.charging) {{
    color: @danger;
    background-color: rgba(240, 128, 128, 0.15);
    border-radius: 6px;
    animation: blink-danger 1.5s ease-in-out infinite;
}}

@keyframes blink-danger {{
    0% {{ background-color: rgba(240, 128, 128, 0.10); }}
    50% {{ background-color: rgba(240, 128, 128, 0.30); }}
    100% {{ background-color: rgba(240, 128, 128, 0.10); }}
}}

#tray {{
    padding-left: 6px;
    padding-right: 4px;
}}

#tray > .passive {{
    -gtk-icon-effect: dim;
}}

#tray > .needs-attention {{
    -gtk-icon-effect: highlight;
    background-color: rgba(240, 128, 128, 0.2);
    border-radius: 6px;
}}

/* ============================================================
   TOOLTIPS — Bento Module Cards
   ============================================================ */
tooltip {{
    background-color: @surface;
    border: 1px solid @overlay;
    border-radius: 10px;
    padding: 8px 12px;
}}

tooltip label {{
    color: @text;
    font-size: 11.5px;
}}
"#,
            self.tokens.background,
            self.tokens.surface,
            self.tokens.overlay,
            self.tokens.text,
            self.tokens.muted,
            self.tokens.primary,
            self.tokens.secondary,
            self.tokens.highlight,
            self.tokens.success,
            self.tokens.warning,
            self.tokens.danger,
            self.tokens.info
        )
    }

    pub fn build_all<P: AsRef<Path>>(&self, root_dir: P) -> Result<(), String> {
        let root = root_dir.as_ref();
        
        let rofi_path = root.join("rofi/theme.rasi");
        fs::write(&rofi_path, self.generate_rofi_theme()).map_err(|e| e.to_string())?;

        let mako_path = root.join("mako/config");
        fs::write(&mako_path, self.generate_mako_config()).map_err(|e| e.to_string())?;

        let kitty_path = root.join("kitty/kitty.conf");
        fs::write(&kitty_path, self.generate_kitty_conf()).map_err(|e| e.to_string())?;

        let waybar_path = root.join("waybar/style.css");
        fs::write(&waybar_path, self.generate_waybar_style()).map_err(|e| e.to_string())?;

        Ok(())
    }

    pub fn apply_runtime<P: AsRef<Path>>(&self, root_dir: P) -> Result<(), String> {
        println!("=== TRANSACTIONAL THEME APPLY ===");
        
        // 1. Validate & Build targets
        self.build_all(root_dir)?;
        println!("[PASS] Theme source validated & targets built.");

        // 2. Waybar: Target-aware hot reload (SIGUSR2)
        if std::process::Command::new("pgrep").arg("-x").arg("waybar").output().map(|o| o.status.success()).unwrap_or(false) {
            let status = std::process::Command::new("pkill")
                .args(["-SIGUSR2", "waybar"])
                .status()
                .map(|s| s.success())
                .unwrap_or(false);
            if status {
                println!("[PASS] Waybar: SIGUSR2 signal sent (Hot reloaded)");
            } else {
                println!("[WARN] Waybar: pkill SIGUSR2 returned non-zero status");
            }
        } else {
            println!("[INFO] Waybar: Not running (applies on launch)");
        }

        // 3. Mako: Target-aware hot reload (makoctl reload)
        if std::process::Command::new("pgrep").arg("-x").arg("mako").output().map(|o| o.status.success()).unwrap_or(false) {
            let status = std::process::Command::new("makoctl").arg("reload").status().map(|s| s.success()).unwrap_or(false);
            if status {
                println!("[PASS] Mako: makoctl reload (Hot reloaded)");
            } else {
                println!("[INFO] Mako: makoctl command unavailable");
            }
        } else {
            println!("[INFO] Mako: Not running (applies on launch)");
        }

        // 4. Kitty: Target-aware hot reload (SIGUSR1)
        if std::process::Command::new("pgrep").arg("-x").arg("kitty").output().map(|o| o.status.success()).unwrap_or(false) {
            let _ = std::process::Command::new("pkill").args(["-SIGUSR1", "kitty"]).status();
            println!("[PASS] Kitty: SIGUSR1 signal sent to active instances");
        } else {
            println!("[INFO] Kitty: Not running (applies on new windows)");
        }

        // 5. Rofi: Next-launch configuration
        println!("[INFO] Rofi: Next-launch configuration updated");

        // 6. Hyprland: Dynamic border keyword update without session restart
        if std::process::Command::new("pgrep").arg("-x").arg("Hyprland").output().map(|o| o.status.success()).unwrap_or(false) {
            let hex_clean = self.tokens.primary.trim_start_matches('#');
            let _ = std::process::Command::new("hyprctl")
                .args(["keyword", "general:col.active_border", &format!("rgba({}FF)", hex_clean)])
                .output();
            println!("[PASS] Hyprland: Active border updated (rgba({}FF))", hex_clean);
        } else {
            println!("[INFO] Hyprland: Not running");
        }

        println!("[PASS] Theme transaction completed successfully.");
        Ok(())
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_waybar_token_reactivity() {
        let mut theme = Theme {
            meta: ThemeMeta {
                name: "test".into(),
                author: "test".into(),
                description: "test".into(),
            },
            tokens: ThemeTokens {
                background: "#0B0E14".into(),
                surface: "#11161F".into(),
                overlay: "#19212D".into(),
                text: "#E8EDF5".into(),
                muted: "#7F899B".into(),
                primary: "#7DD3FC".into(),
                secondary: "#8BA4FF".into(),
                highlight: "#B4A7FF".into(),
                success: "#8BE28B".into(),
                warning: "#E8C77B".into(),
                danger: "#F08080".into(),
                info: "#7DD3FC".into(),
            },
        };

        let style1 = theme.generate_waybar_style();
        assert!(style1.contains("@define-color primary") && style1.contains("#7DD3FC;"));

        theme.tokens.primary = "#FF0000".to_string();
        let style2 = theme.generate_waybar_style();
        assert!(style2.contains("@define-color primary") && style2.contains("#FF0000;"));
        assert_ne!(style1, style2);
    }
}
