use serde::{Deserialize, Serialize};
use std::fs;
use std::path::Path;

#[derive(Debug, Serialize, Deserialize, Clone)]
pub struct ThemeTokens {
    pub background: String,
    pub surface: String,
    pub overlay: String,
    pub text: String,
    pub muted: String,
    pub primary: String,
    pub secondary: String,
    pub highlight: String,
    pub success: String,
    pub warning: String,
    pub danger: String,
    pub info: String,
}

#[derive(Debug, Serialize, Deserialize, Clone)]
pub struct ThemeMeta {
    pub name: String,
    pub author: String,
    pub description: String,
}

#[derive(Debug, Serialize, Deserialize, Clone)]
pub struct Theme {
    pub meta: ThemeMeta,
    pub tokens: ThemeTokens,
}

impl Theme {
    pub fn load_from_file<P: AsRef<Path>>(path: P) -> Result<Self, String> {
        let content = fs::read_to_string(path).map_err(|e| e.to_string())?;
        let theme: Theme = toml::from_str(&content).map_err(|e| e.to_string())?;
        theme.validate()?;
        Ok(theme)
    }

    pub fn validate(&self) -> Result<(), String> {
        let hex_regex =
            |val: &str| -> bool { val.starts_with('#') && (val.len() == 7 || val.len() == 9) };

        let tokens = [
            ("background", &self.tokens.background),
            ("surface", &self.tokens.surface),
            ("overlay", &self.tokens.overlay),
            ("text", &self.tokens.text),
            ("muted", &self.tokens.muted),
            ("primary", &self.tokens.primary),
            ("secondary", &self.tokens.secondary),
            ("highlight", &self.tokens.highlight),
            ("success", &self.tokens.success),
            ("warning", &self.tokens.warning),
            ("danger", &self.tokens.danger),
            ("info", &self.tokens.info),
        ];

        for (name, val) in tokens.iter() {
            if !hex_regex(val) {
                return Err(format!("Invalid hex color for token '{}': {}", name, val));
            }
        }
        Ok(())
    }

    pub fn generate_rofi_theme(&self) -> String {
        format!(
            r#"/**
 * theme.rasi — Bento Minimal Centralized Token Palette
 * Generated by minimalctl — DO NOT edit directly.
 */

* {{
    bg:        {};
    surface:   {};
    overlay:   {};
    fg:        {};
    muted:     {};
    primary:   {};
    secondary: {};
    highlight: {};
    success:   {};
    warning:   {};
    danger:    {};
    info:      {};

    bg-trans:      {}EE;
    surface-trans: {}F2;
    overlay-trans: {}AA;

    font: "AdwaitaMono Nerd Font 10.5";

    background-color: transparent;
    text-color:        @fg;
    margin:  0px;
    padding: 0px;
    spacing: 0px;
}}

window {{
    background-color: @surface-trans;
    border:           1px;
    border-color:     @overlay;
    border-radius:    12px;
}}

mainbox {{
    background-color: transparent;
    padding:          20px;
    spacing:          14px;
}}

inputbar {{
    background-color: @overlay;
    border-radius:    8px;
    padding:          10px 14px;
    spacing:          10px;
    border:           1px;
    border-color:     {}33;
}}

listview {{
    spacing:          4px;
    background-color: transparent;
    border:           0px;
}}

element {{
    padding:          10px 14px;
    border-radius:    12px;
    background-color: @surface;
    border:           1px;
    border-color:     @overlay;
}}

element selected {{
    background-color: @overlay;
    border-color:     @primary;
    text-color:       @fg;
}}

element normal {{
    background-color: transparent;
    text-color:       @fg;
}}
"#,
            self.tokens.background,
            self.tokens.surface,
            self.tokens.overlay,
            self.tokens.text,
            self.tokens.muted,
            self.tokens.primary,
            self.tokens.secondary,
            self.tokens.highlight,
            self.tokens.success,
            self.tokens.warning,
            self.tokens.danger,
            self.tokens.info,
            self.tokens.background,
            self.tokens.surface,
            self.tokens.overlay,
            self.tokens.primary
        )
    }

    pub fn generate_mako_config(&self) -> String {
        format!(
            r#"# Minimal Mako Config — Bento Pill Notifications & OSD
# Generated by minimalctl — DO NOT edit directly.

font=AdwaitaMono Nerd Font 10.5
background-color={0}
text-color={1}
border-color={2}
border-size=1
border-radius=12
padding=12,16
margin=10
width=320
max-visible=3
default-timeout=4000
progress-color=source {3}

[urgency=low]
border-color={4}
default-timeout=2000
text-color={9}

[urgency=normal]
border-color={5}

[urgency=critical]
border-color={6}
default-timeout=0

[app-name="minimal-osd"]
group-by=category
default-timeout=1500
border-color={7}
progress-color=source {8}
"#,
            self.tokens.surface,
            self.tokens.text,
            self.tokens.overlay,
            self.tokens.primary,
            self.tokens.overlay,
            self.tokens.overlay,
            self.tokens.danger,
            self.tokens.overlay,
            self.tokens.primary,
            self.tokens.muted
        )
    }

    pub fn generate_kitty_conf(&self) -> String {
        format!(
            r#"# Minimal Kitty Config — Bento Aesthetics
# Generated by minimalctl — DO NOT edit directly.
font_family      AdwaitaMono Nerd Font
bold_font        auto
italic_font      auto
font_size        11.0

background_opacity 1.0
window_padding_width 12
confirm_os_window_close 0

cursor_shape beam
cursor_blink_interval 0

foreground            {}
background            {}
selection_foreground  {}
selection_background  {}

cursor                {}
cursor_text_color     {}

url_color             {}

color0  {}
color8  {}
color1  {}
color9  {}
color2  {}
color10 {}
color3  {}
color11 {}
color4  {}
color12 {}
color5  {}
color13 {}
color6  {}
color14 {}
color7  {}
color15 {}

active_border_color   {}
inactive_border_color {}
tab_bar_style         powerline
tab_powerline_style   slanted
tab_bar_margin_height 4 0
tab_bar_background    {}
active_tab_background {}
active_tab_foreground {}
inactive_tab_background {}
inactive_tab_foreground {}

allow_remote_control yes
enabled_layouts tall,fat,grid,stack
"#,
            self.tokens.text,
            self.tokens.background,
            self.tokens.background,
            self.tokens.primary,
            self.tokens.primary,
            self.tokens.background,
            self.tokens.secondary,
            self.tokens.surface,
            self.tokens.muted,
            self.tokens.danger,
            self.tokens.danger,
            self.tokens.success,
            self.tokens.success,
            self.tokens.warning,
            self.tokens.warning,
            self.tokens.secondary,
            self.tokens.secondary,
            self.tokens.highlight,
            self.tokens.highlight,
            self.tokens.info,
            self.tokens.primary,
            self.tokens.text,
            self.tokens.text,
            self.tokens.primary,
            self.tokens.overlay,
            self.tokens.background,
            self.tokens.overlay,
            self.tokens.primary,
            self.tokens.surface,
            self.tokens.muted
        )
    }

    pub fn generate_waybar_style(&self) -> String {
        format!(
            r#"/* ============================================================
   MINIMAL BENTO — 3-Pill Waybar Design System
   Generated by minimalctl — DO NOT edit directly.
   ============================================================ */
@define-color background {background};
@define-color surface    {surface};
@define-color overlay    {overlay};
@define-color text       {text};
@define-color muted      {muted};
@define-color primary    {primary};
@define-color secondary  {secondary};
@define-color highlight  {highlight};
@define-color success    {success};
@define-color warning    {warning};
@define-color danger     {danger};
@define-color info       {info};

/* ============================================================
   BASE RESET & TYPOGRAPHY
   ============================================================ */
* {{
    font-family: "AdwaitaMono Nerd Font", "JetBrainsMono NF", monospace;
    font-size: 11.5px;
    font-weight: 600;
    letter-spacing: -0.01em;
    min-height: 0;
    margin: 0;
    padding: 0;
    border: none;
    border-radius: 0;
    color: @text;
}}

window#waybar {{
    background: transparent;
    color: @text;
}}

/* ============================================================
   THREE BENTO PILL CONTAINERS
   ============================================================ */
box#left {{
    background-color: alpha(@surface, 0.92);
    border: 1px solid alpha(@overlay, 0.85);
    border-radius: 12px;
    padding: 0 10px;
    margin: 0;
    min-height: 28px;
}}

box#center {{
    background-color: alpha(@surface, 0.92);
    border: 1px solid alpha(@overlay, 0.85);
    border-radius: 12px;
    padding: 0 14px;
    margin: 0;
    min-height: 28px;
}}

box#right {{
    background-color: alpha(@surface, 0.92);
    border: 1px solid alpha(@overlay, 0.85);
    border-radius: 12px;
    padding: 0 10px;
    margin: 0;
    min-height: 28px;
}}

/* ============================================================
   MODULE BASE LAYOUT & FEEDBACK
   ============================================================ */
#custom-logo,
#custom-security,
#workspaces,
#submap,
#window,
#clock,
#pulseaudio,
#backlight,
#network,
#cpu,
#memory,
#battery,
#tray {{
    padding: 2px 7px;
    margin: 2px 2px;
    border-radius: 6px;
    transition: all 0.2s ease-in-out;
}}

#custom-logo:active,
#custom-security:active,
#workspaces button:active,
#clock:active,
#network:active,
#battery:active,
#pulseaudio:active {{
    background-color: alpha(@text, 0.08);
}}

/* ============================================================
   LEFT PILL — Logo, Workspaces, Window
   ============================================================ */
#custom-logo {{
    color: @primary;
    font-size: 13.5px;
    padding: 2px 8px;
    margin-right: 4px;
}}

#custom-logo:hover {{
    color: @text;
    background-color: alpha(@primary, 0.12);
}}

#workspaces button {{
    padding: 2px 8px;
    margin: 1px 2px;
    color: @muted;
    background: transparent;
    border-radius: 6px;
    border: 1px solid transparent;
    transition: all 0.2s ease;
}}

#workspaces button.active {{
    color: @primary;
    background-color: @overlay;
    border-color: alpha(@primary, 0.40);
}}

#workspaces button.urgent {{
    color: @danger;
    background-color: alpha(@danger, 0.15);
    border-color: alpha(@danger, 0.40);
}}

#workspaces button:hover:not(.active) {{
    background-color: alpha(@text, 0.05);
    color: @text;
}}

#submap {{
    color: @highlight;
    background-color: alpha(@highlight, 0.12);
    border-radius: 6px;
    border: 1px solid alpha(@highlight, 0.30);
    margin-left: 6px;
}}

#window {{
    color: @muted;
    font-weight: 500;
    border-left: 1px solid @overlay;
    margin-left: 6px;
    padding-left: 10px;
}}

/* ============================================================
   CENTER PILL — Clock Anchor
   ============================================================ */
#clock {{
    color: @text;
    font-weight: 600;
    padding: 2px 6px;
}}

#clock:hover {{
    color: @primary;
}}

/* ============================================================
   RIGHT PILL — Metrics & Controls
   ============================================================ */
#custom-security {{
    font-size: 12px;
    padding: 2px 8px;
    margin-right: 4px;
    border-radius: 6px;
}}

#custom-security.secure {{
    color: @success;
}}

#custom-security.warning {{
    color: @warning;
    background-color: alpha(@warning, 0.10);
}}

#custom-security.degraded {{
    color: @danger;
    background-color: alpha(@danger, 0.15);
}}

#custom-security:hover {{
    background-color: alpha(@text, 0.08);
}}

#pulseaudio {{
    color: @muted;
    font-weight: 500;
}}

#pulseaudio.muted {{
    color: @muted;
    opacity: 0.6;
}}

#network {{
    color: @muted;
    font-weight: 500;
}}

#network.disconnected {{
    color: @danger;
    background-color: alpha(@danger, 0.12);
    border-radius: 6px;
}}

/* Discrete Battery States (No Gradients) */
#battery {{
    color: @muted;
    font-weight: 500;
}}

#battery.charging {{
    color: @success;
}}

#battery.warning:not(.charging) {{
    color: @warning;
}}

#battery.critical:not(.charging) {{
    color: @danger;
    background-color: alpha(@danger, 0.15);
    border-radius: 6px;
    animation: blink-danger 1.5s ease-in-out infinite;
}}

@keyframes blink-danger {{
    0% {{ background-color: alpha(@danger, 0.10); }}
    50% {{ background-color: alpha(@danger, 0.30); }}
    100% {{ background-color: alpha(@danger, 0.10); }}
}}

#tray {{
    padding-left: 6px;
    padding-right: 4px;
}}

#tray > .passive {{
    -gtk-icon-effect: dim;
}}

#tray > .needs-attention {{
    -gtk-icon-effect: highlight;
    background-color: alpha(@danger, 0.20);
    border-radius: 6px;
}}

/* ============================================================
   TOOLTIPS — Bento Module Cards
   ============================================================ */
tooltip {{
    background-color: @surface;
    border: 1px solid @overlay;
    border-radius: 10px;
    padding: 8px 12px;
}}

tooltip label {{
    color: @text;
    font-size: 11.5px;
}}
"#,
            background = self.tokens.background,
            surface = self.tokens.surface,
            overlay = self.tokens.overlay,
            text = self.tokens.text,
            muted = self.tokens.muted,
            primary = self.tokens.primary,
            secondary = self.tokens.secondary,
            highlight = self.tokens.highlight,
            success = self.tokens.success,
            warning = self.tokens.warning,
            danger = self.tokens.danger,
            info = self.tokens.info
        )
    }

    pub fn generate_starship_toml(&self) -> String {
        format!(
            r#"# Minimal Starship Config — Bento Prompt Aesthetics
# Generated by minimalctl — DO NOT edit directly.

add_newline = false
command_timeout = 500

format = """
$username\
$directory\
$git_branch\
$git_status\
$package\
$c\
$cmake\
$golang\
$java\
$nodejs\
$python\
$rust\
$cmd_duration\
$line_break\
$character"""

# --- Username ---
[username]
show_always = false
style_user = "bold {}"
format = "[$user]($style) "

# --- Directory ---
[directory]
truncation_length = 3
truncation_symbol = "…/"
home_symbol = "~"
style = "bold {}"
format = "[$path]($style) "

# --- Git Branch ---
[git_branch]
symbol = " "
style = "{}"
format = "on [$symbol$branch]($style) "

# --- Git Status ---
[git_status]
style = "{}"
format = "([$all_status$ahead_behind]($style) )"
conflicted = "="
ahead = "⇡${{count}}"
behind = "⇣${{count}}"
diverged = "⇕⇡${{ahead_count}}⇣${{behind_count}}"
untracked = "?"
stashed = "$"
modified = "*"
staged = "+"
renamed = "»"
deleted = "✘"

# --- Languages / Toolchains ---
[c]
symbol = " "
style = "{}"
format = "[$symbol$version]($style) "

[golang]
symbol = " "
style = "{}"
format = "[$symbol$version]($style) "

[java]
symbol = " "
style = "{}"
format = "[$symbol$version]($style) "

[nodejs]
symbol = " "
style = "{}"
format = "[$symbol$version]($style) "

[python]
symbol = " "
style = "{}"
format = "[$symbol$version]($style) "

[rust]
symbol = " "
style = "{}"
format = "[$symbol$version]($style) "

# --- Execution Time ---
[cmd_duration]
min_time = 2_000
style = "{}"
format = "took [$duration]($style) "

# --- Prompt Character ---
[character]
success_symbol = "[λ](bold {})"
error_symbol = "[λ](bold {})"
"#,
            self.tokens.primary,
            self.tokens.primary,
            self.tokens.muted,
            self.tokens.danger,
            self.tokens.muted,
            self.tokens.muted,
            self.tokens.muted,
            self.tokens.muted,
            self.tokens.muted,
            self.tokens.muted,
            self.tokens.muted,
            self.tokens.primary,
            self.tokens.danger
        )
    }

    pub fn generate_btop_theme(&self) -> String {
        format!(
            r#"# btop tty theme — Minimal Bento
# Generated by minimalctl — DO NOT edit directly.

# Main UI Element Colors
theme[main_bg]="{}"
theme[main_fg]="{}"
theme[title]="{}"
theme[hi_fg]="{}"
theme[selected_bg]="{}"
theme[selected_fg]="{}"
theme[inactive_fg]="{}"
theme[graph_text]="{}"
theme[proc_misc]="{}"

# Box Outlines
theme[cpu_box]="{}"
theme[mem_box]="{}"
theme[net_box]="{}"
theme[proc_box]="{}"
theme[div_line]="{}"

# CPU Graph Colors
theme[cpu_start]="{}"
theme[cpu_mid]="{}"
theme[cpu_end]="{}"

# Temperature Colors
theme[temp_start]="{}"
theme[temp_mid]="{}"
theme[temp_end]="{}"

# Mem/Disk free meter
theme[free_start]="{}"
theme[free_mid]="{}"
theme[free_end]="{}"

# Mem/Disk cached meter
theme[cached_start]="{}"
theme[cached_mid]="{}"
theme[cached_end]="{}"

# Mem/Disk available meter
theme[available_start]="{}"
theme[available_mid]="{}"
theme[available_end]="{}"

# Mem/Disk used meter
theme[used_start]="{}"
theme[used_mid]="{}"
theme[used_end]="{}"

# Download graph colors
theme[download_start]="{}"
theme[download_mid]="{}"
theme[download_end]="{}"

# Upload graph colors
theme[upload_start]="{}"
theme[upload_mid]="{}"
theme[upload_end]="{}"
"#,
            self.tokens.background,
            self.tokens.text,
            self.tokens.primary,
            self.tokens.primary,
            self.tokens.overlay,
            self.tokens.text,
            self.tokens.muted,
            self.tokens.muted,
            self.tokens.secondary,
            self.tokens.overlay,
            self.tokens.overlay,
            self.tokens.overlay,
            self.tokens.overlay,
            self.tokens.overlay,
            self.tokens.primary,
            self.tokens.secondary,
            self.tokens.highlight,
            self.tokens.success,
            self.tokens.warning,
            self.tokens.danger,
            self.tokens.primary,
            self.tokens.secondary,
            self.tokens.primary,
            self.tokens.secondary,
            self.tokens.highlight,
            self.tokens.primary,
            self.tokens.primary,
            self.tokens.secondary,
            self.tokens.primary,
            self.tokens.highlight,
            self.tokens.warning,
            self.tokens.danger,
            self.tokens.primary,
            self.tokens.secondary,
            self.tokens.primary,
            self.tokens.highlight,
            self.tokens.secondary,
            self.tokens.primary
        )
    }

    pub fn generate_nvim_theme(&self) -> String {
        format!(
            r#"---@type Base46Theme
-- lua/themes/minimal.lua — Base46 theme for NvChad
-- Generated by minimalctl — DO NOT edit directly.

local M = {{}}

M.base_30 = {{
  white         = "{}",
  darker_black  = "{}",
  black         = "{}",
  black2        = "{}",
  one_bg        = "{}",
  one_bg2       = "{}",
  one_bg3       = "{}",
  grey          = "{}",
  grey_fg       = "{}",
  grey_fg2      = "{}",
  light_grey    = "{}",
  red           = "{}",
  baby_pink     = "{}",
  pink          = "{}",
  line          = "{}",
  green         = "{}",
  vibrant_green = "{}",
  nord_blue     = "{}",
  blue          = "{}",
  yellow        = "{}",
  sun           = "{}",
  purple        = "{}",
  dark_purple   = "{}",
  teal          = "{}",
  orange        = "{}",
  cyan          = "{}",
  statusline_bg = "{}",
  lightbg       = "{}",
  pmenu_bg      = "{}",
  folder_bg     = "{}",
}}

M.base_16 = {{
  base00 = "{}",
  base01 = "{}",
  base02 = "{}",
  base03 = "{}",
  base04 = "{}",
  base05 = "{}",
  base06 = "{}",
  base07 = "{}",
  base08 = "{}",
  base09 = "{}",
  base0A = "{}",
  base0B = "{}",
  base0C = "{}",
  base0D = "{}",
  base0E = "{}",
  base0F = "{}",
}}

M.type = "dark"

return M
"#,
            self.tokens.text,
            self.tokens.background,
            self.tokens.background,
            self.tokens.surface,
            self.tokens.surface,
            self.tokens.overlay,
            self.tokens.overlay,
            self.tokens.muted,
            self.tokens.muted,
            self.tokens.muted,
            self.tokens.muted,
            self.tokens.danger,
            self.tokens.danger,
            self.tokens.highlight,
            self.tokens.overlay,
            self.tokens.success,
            self.tokens.success,
            self.tokens.secondary,
            self.tokens.secondary,
            self.tokens.warning,
            self.tokens.warning,
            self.tokens.highlight,
            self.tokens.highlight,
            self.tokens.info,
            self.tokens.warning,
            self.tokens.primary,
            self.tokens.surface,
            self.tokens.overlay,
            self.tokens.primary,
            self.tokens.secondary,
            self.tokens.background,
            self.tokens.surface,
            self.tokens.overlay,
            self.tokens.muted,
            self.tokens.muted,
            self.tokens.text,
            self.tokens.text,
            self.tokens.text,
            self.tokens.danger,
            self.tokens.warning,
            self.tokens.warning,
            self.tokens.success,
            self.tokens.info,
            self.tokens.secondary,
            self.tokens.highlight,
            self.tokens.danger
        )
    }

    pub fn generate_hypr_colors(&self) -> String {
        let clean = |hex: &str| -> String { hex.trim_start_matches('#').to_string() };
        format!(
            r#"# Hyprland color variables
# Generated by minimalctl — DO NOT edit directly.
$background = rgba({}FF)
$surface    = rgba({}FF)
$overlay    = rgba({}FF)
$text       = rgba({}FF)
$muted      = rgba({}FF)
$primary    = rgba({}FF)
$secondary  = rgba({}FF)
$highlight  = rgba({}FF)
$success    = rgba({}FF)
$warning    = rgba({}FF)
$danger     = rgba({}FF)
$info       = rgba({}FF)
"#,
            clean(&self.tokens.background),
            clean(&self.tokens.surface),
            clean(&self.tokens.overlay),
            clean(&self.tokens.text),
            clean(&self.tokens.muted),
            clean(&self.tokens.primary),
            clean(&self.tokens.secondary),
            clean(&self.tokens.highlight),
            clean(&self.tokens.success),
            clean(&self.tokens.warning),
            clean(&self.tokens.danger),
            clean(&self.tokens.info)
        )
    }

    pub fn generate_tmux_conf(&self) -> String {
        format!(
            r##"# ===========================================================================
#  TMUX CONFIGURATION — Minimal Theme (Optimized)
#  Generated by minimalctl — DO NOT edit directly.
# ===========================================================================

set -s escape-time 0
set -g history-limit 50000
set -g mouse on

set -g default-terminal "tmux-256color"
set -as terminal-features ",xterm-256color:RGB"
set -as terminal-features ",xterm-kitty:RGB"
set -as terminal-features ",alacritty:RGB"
set -ag terminal-overrides ",xterm-256color:Tc"

set -g focus-events on
set -sg repeat-time 400

unbind C-b
set -g prefix C-a
bind C-a send-prefix

bind r source-file ~/.config/tmux/tmux.conf \; display-message "  tmux.conf reloaded"

unbind '"'
unbind %
bind | split-window -h -c "#{{pane_current_path}}"
bind v split-window -h -c "#{{pane_current_path}}"
bind - split-window -v -c "#{{pane_current_path}}"
bind _ split-window -v -c "#{{pane_current_path}}"
bind c new-window -c "#{{pane_current_path}}"

bind -n M-h select-pane -L
bind -n M-j select-pane -D
bind -n M-k select-pane -U
bind -n M-l select-pane -R

bind -r h select-pane -L
bind -r j select-pane -D
bind -r k select-pane -U
bind -r l select-pane -R

bind -r H resize-pane -L 5
bind -r J resize-pane -D 5
bind -r K resize-pane -U 5
bind -r L resize-pane -R 5

bind m resize-pane -Z
bind = select-layout even-horizontal
bind + select-layout even-vertical

set -g base-index 1
setw -g pane-base-index 1
set -g renumber-windows on

setw -g mode-keys vi
set -g set-clipboard on

bind -T copy-mode-vi v send-keys -X begin-selection
bind -T copy-mode-vi y send-keys -X copy-selection-and-cancel
bind -T copy-mode-vi Escape send-keys -X cancel
bind -T copy-mode-vi q      send-keys -X cancel

bind -n WheelUpPane if-shell -F "#{{||:#{{pane_in_mode}},#{{mouse_any_flag}}}}" \
    "send-keys -M" \
    "copy-mode -e"

bind -T copy-mode-vi MouseDrag1Pane send-keys -X begin-selection
bind -T copy-mode-vi MouseDragEnd1Pane send-keys -X copy-selection-and-cancel
bind -T copy-mode-vi DoubleClick1Pane \
    select-pane \; send-keys -X select-word \; send-keys -X copy-selection-and-cancel
bind -T copy-mode-vi TripleClick1Pane \
    select-pane \; send-keys -X select-line \; send-keys -X copy-selection-and-cancel

setw -g monitor-activity on
set -g visual-activity off
set -g visual-bell off
set -g visual-silence off
set -g bell-action none

bind C-k send-keys -X cancel 2>/dev/null \; send-keys 'clear' Enter
bind X send-keys 'reset' Enter
bind -n M-Escape send-keys -X cancel 2>/dev/null

# --- MINIMAL STATUS BAR THEME ---
set -g status-position bottom
set -g status-interval 15

set -g status-style "fg={},bg={}"

set -g status-left-length 30
set -g status-right-length 60

set -g status-left "#[fg={},bg={},bold] #S #[fg={},bg={},nobold] "
set -g status-right "#[fg={},bg={}]  #h  #[fg={},bg={},bold] %H:%M "

set -g status-justify left
setw -g window-status-separator " "

setw -g window-status-format "#[fg={},bg={}] #I  #W "
setw -g window-status-current-format "#[fg={},bg={},bold] #I  #W#{{?window_zoomed_flag, 󰁌 , }} "
setw -g window-status-activity-style "fg={},bg={}"

set -g pane-border-style "fg={}"
set -g pane-active-border-style "fg={}"

set -g message-style "fg={},bg={},bold"
setw -g clock-mode-colour "{}"
set -g mode-style "fg={},bg={}"
"##,
            self.tokens.muted,
            self.tokens.surface,
            self.tokens.surface,
            self.tokens.primary,
            self.tokens.primary,
            self.tokens.surface,
            self.tokens.text,
            self.tokens.overlay,
            self.tokens.background,
            self.tokens.primary,
            self.tokens.muted,
            self.tokens.surface,
            self.tokens.primary,
            self.tokens.overlay,
            self.tokens.danger,
            self.tokens.surface,
            self.tokens.overlay,
            self.tokens.primary,
            self.tokens.text,
            self.tokens.overlay,
            self.tokens.primary,
            self.tokens.background,
            self.tokens.primary
        )
    }

    pub fn generate_wlogout_style(&self) -> String {
        format!(
            r#"/**
 * style.css — Bento Minimal Token Compiled Wlogout Palette
 * Generated by minimalctl — DO NOT edit directly.
 */

* {{
    background-image: none;
    box-shadow: none;
    font-family: "AdwaitaMono Nerd Font", monospace;
    font-size: 14px;
    font-weight: bold;
    transition: all 0.2s cubic-bezier(0.16, 1, 0.3, 1);
}}

window {{
    background-color: rgba(11, 14, 20, 0.85);
}}

button {{
    color: {};
    background-color: {};
    border: 1px solid {};
    border-radius: 16px;
    margin: 10px;
    padding: 16px;
    background-repeat: no-repeat;
    background-position: center 30%;
    background-size: 28%;
}}

button:focus, button:active, button:hover {{
    background-color: {};
    border: 2px solid {};
    color: {};
    box-shadow: 0 0 16px {}4D;
}}

#lock {{
    background-image: image(url("/usr/share/wlogout/icons/lock.png"), url("/usr/local/share/wlogout/icons/lock.png"));
}}

#logout {{
    background-image: image(url("/usr/share/wlogout/icons/logout.png"), url("/usr/local/share/wlogout/icons/logout.png"));
}}

#suspend {{
    background-image: image(url("/usr/share/wlogout/icons/suspend.png"), url("/usr/local/share/wlogout/icons/suspend.png"));
}}

#hibernate {{
    background-image: image(url("/usr/share/wlogout/icons/hibernate.png"), url("/usr/local/share/wlogout/icons/hibernate.png"));
}}

#shutdown {{
    background-image: image(url("/usr/share/wlogout/icons/shutdown.png"), url("/usr/local/share/wlogout/icons/shutdown.png"));
}}

#reboot {{
    background-image: image(url("/usr/share/wlogout/icons/reboot.png"), url("/usr/local/share/wlogout/icons/reboot.png"));
}}
"#,
            self.tokens.text,
            self.tokens.surface,
            self.tokens.overlay,
            self.tokens.overlay,
            self.tokens.primary,
            self.tokens.primary,
            self.tokens.primary
        )
    }

    pub fn atomic_write<P: AsRef<Path>>(path: P, content: &str) -> Result<(), String> {
        let path = path.as_ref();
        let parent = path
            .parent()
            .ok_or_else(|| format!("Invalid parent directory for path: {}", path.display()))?;
        if !parent.exists() {
            fs::create_dir_all(parent)
                .map_err(|e| format!("Failed to create directory {}: {}", parent.display(), e))?;
        }

        let file_name = path
            .file_name()
            .and_then(|f| f.to_str())
            .unwrap_or("target");
        let tmp_path = parent.join(format!(".{}.tmp", file_name));

        {
            use std::io::Write;
            let mut file = fs::File::create(&tmp_path)
                .map_err(|e| format!("Failed to create temp file {}: {}", tmp_path.display(), e))?;
            file.write_all(content.as_bytes())
                .map_err(|e| format!("Failed to write to temp file {}: {}", tmp_path.display(), e))?;
            file.flush()
                .map_err(|e| format!("Flush error on {}: {}", tmp_path.display(), e))?;
            file.sync_all()
                .map_err(|e| format!("fsync error on {}: {}", tmp_path.display(), e))?;
        }

        fs::rename(&tmp_path, path)
            .map_err(|e| format!("Atomic rename failed for {}: {}", path.display(), e))?;
        Ok(())
    }

    pub fn compute_hash(&self) -> String {
        let mut hash: u64 = 0xcbf29ce484222325;
        let bytes = format!(
            "{}:{}:{}:{}:{}:{}:{}:{}:{}:{}:{}:{}:{}",
            self.meta.name,
            self.tokens.background,
            self.tokens.surface,
            self.tokens.overlay,
            self.tokens.text,
            self.tokens.muted,
            self.tokens.primary,
            self.tokens.secondary,
            self.tokens.highlight,
            self.tokens.success,
            self.tokens.warning,
            self.tokens.danger,
            self.tokens.info
        );
        for byte in bytes.bytes() {
            hash ^= u64::from(byte);
            hash = hash.wrapping_mul(0x100000001b3);
        }
        format!("{:016x}", hash)
    }

    pub fn build_all<P: AsRef<Path>>(&self, root_dir: P) -> Result<(), String> {
        let root = root_dir.as_ref();

        Self::atomic_write(root.join("rofi/theme.rasi"), &self.generate_rofi_theme())?;
        Self::atomic_write(root.join("mako/config"), &self.generate_mako_config())?;
        Self::atomic_write(root.join("kitty/kitty.conf"), &self.generate_kitty_conf())?;
        Self::atomic_write(root.join("waybar/style.css"), &self.generate_waybar_style())?;
        Self::atomic_write(root.join("starship/starship.toml"), &self.generate_starship_toml())?;
        Self::atomic_write(root.join("btop/btop.theme"), &self.generate_btop_theme())?;
        Self::atomic_write(root.join("hypr/colors.conf"), &self.generate_hypr_colors())?;
        Self::atomic_write(root.join("tmux/tmux.conf"), &self.generate_tmux_conf())?;

        let wlogout_dir = root.join("wlogout");
        if wlogout_dir.exists() {
            Self::atomic_write(wlogout_dir.join("style.css"), &self.generate_wlogout_style())?;
        }

        let nvim_theme_dir = root.join("nvim/lua/themes");
        if nvim_theme_dir.exists() {
            Self::atomic_write(nvim_theme_dir.join("minimal.lua"), &self.generate_nvim_theme())?;
        }

        Ok(())
    }

    pub fn backup_state<P: AsRef<Path>>(&self, root_dir: P) -> Result<(), String> {
        let root = root_dir.as_ref();
        let backup_dir = root.join(".rollback_backup");
        if backup_dir.exists() {
            let _ = fs::remove_dir_all(&backup_dir);
        }
        fs::create_dir_all(&backup_dir).map_err(|e| e.to_string())?;

        let files = [
            "rofi/theme.rasi",
            "mako/config",
            "kitty/kitty.conf",
            "waybar/style.css",
            "starship/starship.toml",
            "btop/btop.theme",
            "hypr/colors.conf",
            "tmux/tmux.conf",
        ];

        for rel in files.iter() {
            let src = root.join(rel);
            if src.exists() {
                let dest = backup_dir.join(rel.replace('/', "_"));
                let _ = fs::copy(&src, &dest);
            }
        }

        let nvim_src = root.join("nvim/lua/themes/minimal.lua");
        if nvim_src.exists() {
            let _ = fs::copy(&nvim_src, backup_dir.join("nvim_lua_themes_minimal.lua"));
        }

        Ok(())
    }

    pub fn perform_rollback<P: AsRef<Path>>(root_dir: P) -> Result<(), String> {
        let root = root_dir.as_ref();
        let backup_dir = root.join(".rollback_backup");
        if !backup_dir.exists() {
            return Err("No rollback backup state found. Apply a theme first.".to_string());
        }

        let files = [
            ("rofi_theme.rasi", "rofi/theme.rasi"),
            ("mako_config", "mako/config"),
            ("kitty_kitty.conf", "kitty/kitty.conf"),
            ("waybar_style.css", "waybar/style.css"),
            ("starship_starship.toml", "starship/starship.toml"),
            ("btop_btop.theme", "btop/btop.theme"),
            ("hypr_colors.conf", "hypr/colors.conf"),
            ("tmux_tmux.conf", "tmux/tmux.conf"),
            ("nvim_lua_themes_minimal.lua", "nvim/lua/themes/minimal.lua"),
        ];

        for (bak_name, target_rel) in files.iter() {
            let bak_file = backup_dir.join(bak_name);
            if bak_file.exists() {
                let target_file = root.join(target_rel);
                if let Ok(content) = fs::read_to_string(&bak_file) {
                    Self::atomic_write(&target_file, &content)?;
                }
            }
        }

        println!("[minimalctl] Rollback executed successfully.");
        Ok(())
    }

    pub fn apply_runtime<P: AsRef<Path>>(&self, root_dir: P) -> Result<(), String> {
        let root = root_dir.as_ref();
        println!("=== TRANSACTIONAL THEME APPLY ===");

        // 1. Validate & Build targets
        self.build_all(root)?;
        println!("[PASS] Theme source validated & targets built.");

        // 2. Waybar: Target-aware reload (restarts Waybar process to load compiled GTK style.css)
        let waybar_was_running = std::process::Command::new("pgrep")
            .arg("-x")
            .arg("waybar")
            .output()
            .map(|o| o.status.success())
            .unwrap_or(false);
        if waybar_was_running {
            let _ = std::process::Command::new("pkill")
                .args(["-x", "waybar"])
                .output();
            std::thread::sleep(std::time::Duration::from_millis(200));
            if std::process::Command::new("pgrep")
                .arg("-x")
                .arg("Hyprland")
                .output()
                .map(|o| o.status.success())
                .unwrap_or(false)
            {
                let _ = std::process::Command::new("hyprctl")
                    .args(["dispatch", "exec", "waybar"])
                    .output();
            } else {
                let _ = std::process::Command::new("waybar").spawn();
            }
            println!("[PASS] Waybar: Restarted with new style.css");
        } else {
            println!("[INFO] Waybar: Not running (applies on launch)");
        }

        // 3. Mako: Target-aware hot reload (makoctl reload)
        if std::process::Command::new("pgrep")
            .arg("-x")
            .arg("mako")
            .output()
            .map(|o| o.status.success())
            .unwrap_or(false)
        {
            let status = std::process::Command::new("makoctl")
                .arg("reload")
                .status()
                .map(|s| s.success())
                .unwrap_or(false);
            if status {
                println!("[PASS] Mako: makoctl reload (Hot reloaded)");
            } else {
                println!("[INFO] Mako: makoctl command unavailable");
            }
        } else {
            println!("[INFO] Mako: Not running (applies on launch)");
        }

        // 4. Kitty: Target-aware hot reload (SIGUSR1)
        if std::process::Command::new("pgrep")
            .arg("-x")
            .arg("kitty")
            .output()
            .map(|o| o.status.success())
            .unwrap_or(false)
        {
            let _ = std::process::Command::new("pkill")
                .args(["-SIGUSR1", "kitty"])
                .status();
            println!("[PASS] Kitty: SIGUSR1 signal sent to active instances");
        } else {
            println!("[INFO] Kitty: Not running (applies on new windows)");
        }

        // 5. Rofi: Next-launch configuration
        println!("[INFO] Rofi: Next-launch configuration updated");

        // 6. Hyprland: Dynamic border keyword update without session restart
        if std::process::Command::new("pgrep")
            .arg("-x")
            .arg("Hyprland")
            .output()
            .map(|o| o.status.success())
            .unwrap_or(false)
        {
            let hex_clean = self.tokens.primary.trim_start_matches('#');
            let _ = std::process::Command::new("hyprctl")
                .args([
                    "keyword",
                    "general:col.active_border",
                    &format!("rgba({}FF)", hex_clean),
                ])
                .output();
            println!(
                "[PASS] Hyprland: Active border updated (rgba({}FF))",
                hex_clean
            );
        } else {
            println!("[INFO] Hyprland: Not running");
        }

        // 7. Tmux: Target-aware hot reload (tmux source-file + refresh-client)
        let tmux_active = std::process::Command::new("tmux")
            .arg("ls")
            .output()
            .map(|o| o.status.success())
            .unwrap_or(false);

        if tmux_active {
            let tmux_conf = std::fs::canonicalize(root.join("tmux/tmux.conf"))
                .unwrap_or_else(|_| root.join("tmux/tmux.conf"));
            let _ = std::process::Command::new("tmux")
                .args([
                    "source-file",
                    tmux_conf.to_str().unwrap_or("tmux/tmux.conf"),
                ])
                .output();
            if let Ok(home) = std::env::var("HOME") {
                let _ = std::process::Command::new("tmux")
                    .args(["source-file", &format!("{}/.tmux.conf", home)])
                    .output();
            }
            let _ = std::process::Command::new("tmux")
                .args(["refresh-client", "-S"])
                .output();
            let _ = std::process::Command::new("tmux")
                .args(["refresh-client", "-a"])
                .output();
            println!("[PASS] Tmux: Sourced tmux.conf & refreshed active sessions live");
        } else {
            println!("[INFO] Tmux: Server not running (applies on next session)");
        }

        println!("[PASS] Theme transaction completed successfully.");
        Ok(())
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_waybar_token_reactivity() {
        let mut theme = Theme {
            meta: ThemeMeta {
                name: "test".into(),
                author: "test".into(),
                description: "test".into(),
            },
            tokens: ThemeTokens {
                background: "#0B0E14".into(),
                surface: "#11161F".into(),
                overlay: "#19212D".into(),
                text: "#E8EDF5".into(),
                muted: "#7F899B".into(),
                primary: "#7DD3FC".into(),
                secondary: "#8BA4FF".into(),
                highlight: "#B4A7FF".into(),
                success: "#8BE28B".into(),
                warning: "#E8C77B".into(),
                danger: "#F08080".into(),
                info: "#7DD3FC".into(),
            },
        };

        let style1 = theme.generate_waybar_style();
        assert!(style1.contains("@define-color primary") && style1.contains("#7DD3FC;"));

        theme.tokens.primary = "#FF0000".to_string();
        let style2 = theme.generate_waybar_style();
        assert!(style2.contains("@define-color primary") && style2.contains("#FF0000;"));
        assert_ne!(style1, style2);
    }

    #[test]
    fn test_theme_validation_hex_format() {
        let mut theme = Theme {
            meta: ThemeMeta {
                name: "test".into(),
                author: "test".into(),
                description: "test".into(),
            },
            tokens: ThemeTokens {
                background: "#0B0E14".into(),
                surface: "#11161F".into(),
                overlay: "#19212D".into(),
                text: "#E8EDF5".into(),
                muted: "#7F899B".into(),
                primary: "#7DD3FC".into(),
                secondary: "#8BA4FF".into(),
                highlight: "#B4A7FF".into(),
                success: "#8BE28B".into(),
                warning: "#E8C77B".into(),
                danger: "#F08080".into(),
                info: "#7DD3FC".into(),
            },
        };
        assert!(theme.validate().is_ok());

        theme.tokens.background = "invalid-hex".to_string();
        assert!(theme.validate().is_err());
    }

    #[test]
    fn test_atomic_write() {
        let temp_dir = std::env::temp_dir().join("minimalctl_test_atomic");
        let test_file = temp_dir.join("test_target.txt");
        let content = "hello atomic world";
        assert!(Theme::atomic_write(&test_file, content).is_ok());
        assert_eq!(fs::read_to_string(&test_file).unwrap(), content);
        let _ = fs::remove_dir_all(&temp_dir);
    }

    #[test]
    fn test_compute_hash_determinism() {
        let theme = Theme {
            meta: ThemeMeta {
                name: "obsidian".into(),
                author: "Hypokoto".into(),
                description: "Test".into(),
            },
            tokens: ThemeTokens {
                background: "#0B0E14".into(),
                surface: "#11161F".into(),
                overlay: "#19212D".into(),
                text: "#E8EDF5".into(),
                muted: "#7F899B".into(),
                primary: "#7DD3FC".into(),
                secondary: "#8BA4FF".into(),
                highlight: "#B4A7FF".into(),
                success: "#8BE28B".into(),
                warning: "#E8C77B".into(),
                danger: "#F08080".into(),
                info: "#7DD3FC".into(),
            },
        };

        let hash1 = theme.compute_hash();
        let hash2 = theme.compute_hash();
        assert_eq!(hash1, hash2);
        assert_eq!(hash1.len(), 16);
    }
}
